CREATE TABLE "ZSTUDENT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"AGE" NUMBER, 
	 CONSTRAINT "ZSTUDENT_PK" PRIMARY KEY ("ID")
   );

CREATE TABLE "ZMARKS" 
   (	"SID" NUMBER NOT NULL ENABLE, 
	"MARKS" NUMBER, 
	"YEAR" NUMBER, 
	 CONSTRAINT "ZMARKS_PK" PRIMARY KEY ("SID")
   );