
package com.example.ws.student;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-10-29T18:30:57.966+05:30
 * Generated source version: 2.5.2
 * 
 */
 
public class StudentPortType_StudentPort_Server{

    protected StudentPortType_StudentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new StudentPortTypeImpl();
        String address = "http://localhost:8080/SoapWS/services/StudentService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new StudentPortType_StudentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
